## Development Playground Configuration
## This file defines pipeline runs for testing and development

# Default settings
defaults:
  data_dir: "data"
  cache_dir: "dev_cache"
  device: "cuda"

# Predefined pipeline configurations
pipelines:
  # DMX Voice Separation Pipeline with Post-Processing
  dmx_separation:
    description: "Process DMX FLAC file with enhanced voice separation and cleanup"
    stages:
      - stage: AudioPreprocessor
        config:
          target_sr: 44100
          normalize: true
        inputs:
          file_path: "data/dmx.flac"
      
      - stage: EnhancedVoiceSeparator
        config:
          model_name: "htdemucs_ft"
          quality_mode: "high"
          overlap: 0.75
          shifts: 3
        depends_on: AudioPreprocessor
      
      - stage: AudioPostProcessor
        config:
          input_sources: ["vocals"]
          preset: "vocal"
          output_suffix: "_clean"
          # Vocal-specific tuning
          high_pass_cutoff: 85          # Remove low-end muddiness from vocals
          noise_gate_threshold: -55     # Moderate gating for speech pauses
          spectral_enhancement: true    # Enhance vocal presence and clarity
          preemphasis_coeff: 0.95      # Boost high frequencies for speech intelligibility
          dynamic_compression: true    # Even out vocal dynamics
          compression_threshold: -18   # Start compression early for consistency
          compression_ratio: 3.5       # Good ratio for speech consistency
          limiter_threshold: -0.3      # Prevent harsh vocal peaks
        depends_on: EnhancedVoiceSeparator
      
      - stage: AudioPostProcessor
        config:
          input_sources: ["music"]
          preset: "music"
          output_suffix: "_clean"
          # Music-specific tuning
          high_pass_cutoff: 30          # Preserve musical low-end (bass, kick)
          noise_gate_threshold: -65     # Gentle gating to preserve musical decay
          spectral_enhancement: false  # Preserve natural musical timbre
          dynamic_compression: true    # Light compression to glue the mix
          compression_threshold: -22   # Higher threshold to preserve dynamics
          compression_ratio: 2.5       # Musical ratio that preserves dynamics
          limiter_threshold: -0.5      # Prevent clipping while preserving peaks
        depends_on: EnhancedVoiceSeparator

  # Host Sample Processing Pipeline  
  host_processing:
    description: "Full pipeline processing of host sample"
    stages:
      - stage: AudioPreprocessor
        config:
          target_sr: 44100
          normalize: true
        inputs:
          file_path: "data/host_sample.wav"
      
      - stage: VoiceSeparator
        config:
          model_name: "htdemucs_ft"
        depends_on: AudioPreprocessor
      
      - stage: SpeakerDiarizer
        depends_on: VoiceSeparator
      
      - stage: SpeechRecognizer
        config:
          model_size: "base"
          language: "en"
        depends_on: [VoiceSeparator, SpeakerDiarizer]

  # Compare Separation Models
  separation_comparison:
    description: "Compare different separation models on the same audio"
    stages:
      - stage: AudioPreprocessor
        config:
          target_sr: 44100
          normalize: true
        inputs:
          file_path: "data/dmx.flac"
      
      - stage: VoiceSeparator
        config:
          model_name: "htdemucs_ft"
        depends_on: AudioPreprocessor
        
      - stage: EnhancedVoiceSeparator
        config:
          model_name: "htdemucs_ft"
        depends_on: AudioPreprocessor
        
      - stage: SepformerSeparator
        config:
          model_name: "speechbrain/sepformer-whamr"
        depends_on: AudioPreprocessor
  # Quick Test Pipeline with Post-Processing
  quick_test:
    description: "Quick test with short audio for rapid iteration"
    stages:
      - stage: AudioPreprocessor
        config:
          target_sr: 44100
          normalize: true
        inputs:
          file_path: "data/test_audio.wav"
      - stage: EnhancedVoiceSeparator
        config:
          model_name: "htdemucs_ft"
          quality_mode: "balanced"
        depends_on: AudioPreprocessor
      
      - stage: AudioPostProcessor
        config:
          input_sources: ["auto"]  # Process all available sources
          preset: "enhance"         # Balanced enhancement
          output_suffix: "_enhanced"
        depends_on: EnhancedVoiceSeparator

# Individual stage configurations for standalone testing
stages:
  AudioPreprocessor:
    default_config:
      target_sr: 44100
      normalize: true
    test_inputs:
      - "data/dmx.flac"
      - "data/host_sample.wav" 
      - "data/test_audio.wav"

  VoiceSeparator:
    default_config:
      model_name: "htdemucs_ft"
    model_options:
      - "htdemucs"
      - "htdemucs_ft" 
      - "htdemucs_6s"

  EnhancedVoiceSeparator:
    default_config:
      model_name: "htdemucs_ft"
    model_options:
      - "htdemucs"
      - "htdemucs_ft"
      - "htdemucs_6s"

  SpeakerDiarizer:
    default_config:
      min_speakers: 1
      max_speakers: 10

  SpeechRecognizer:
    default_config:
      model_size: "base"
      language: "en"
    model_options:
      - "tiny"
      - "base" 
      - "small"
      - "medium"
      - "large"

  AudioPostProcessor:
    default_config:
      preset: "enhance"
      input_sources: ["auto"]
      output_suffix: "_enhanced"
    preset_options:
      - "clean"      # Light processing for good quality audio
      - "enhance"    # Balanced processing [DEFAULT]
      - "aggressive" # Heavy processing for problem audio
      - "vocal"      # Optimized for speech/vocals
      - "music"      # Preserve musical character
    tuning_examples:
      vocal_cleanup:
        preset: "vocal"
        high_pass_cutoff: 85
        noise_gate_threshold: -55
        spectral_enhancement: true
        preemphasis_coeff: 0.95
        compression_ratio: 3.5
        limiter_threshold: -0.3
      music_cleanup:
        preset: "music"
        high_pass_cutoff: 30
        noise_gate_threshold: -65
        spectral_enhancement: false
        compression_ratio: 2.5
        limiter_threshold: -0.5

# Testing scenarios
test_scenarios:
  dmx_voice_separation:
    pipeline: dmx_separation
    expected_outputs:
      - vocals.wav
      - music.wav
    validation:
      min_duration_seconds: 200
      max_duration_seconds: 250
      
  model_comparison:
    pipeline: separation_comparison
    compare_outputs:
      - VoiceSeparator.vocals
      - EnhancedVoiceSeparator.vocals
      - SepformerSeparator.source1
    metrics:
      - separation_quality
      - processing_time
      - gpu_memory_usage